package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adrestype generated by hbm2java
 */
@Entity
@Table(name="adrestype"
    ,catalog="workshop2"
)
public class Adrestype  implements java.io.Serializable {


    private Long idAdresType;
    private String type;
    private Set<Adres> adreses = new HashSet<>(0);

    public Adrestype() {
    }

    public Adrestype(String type, Set<Adres> adreses) {
       this.type = type;
       this.adreses = adreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_adrestype", unique=true, nullable=false)
    public Long getIdAdresType() {
        return this.idAdresType;
    }
    
    public void setIdAdresType(Long idAdresType) {
        this.idAdresType = idAdresType;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="adrestype")
    public Set<Adres> getAdreses() {
        return this.adreses;
    }
    
    public void setAdreses(Set<Adres> adreses) {
        this.adreses = adreses;
    }




}


