package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adres generated by hbm2java
 */
@Entity
@Table(name="adres"
    ,catalog="workshop2"
)
public class Adres implements java.io.Serializable {


     private Long idAdres;
     private Adrestype adrestype;
     private String straatnaam;
     private String postcode;
     private String toevoeging;
     private Long huisnummer;
     private String woonplaats;
     private Set<KlantHasAdres> klantHasAdreses = new HashSet<>(0);

    public Adres() {
    }

    public Adres(Adrestype adrestype, String straatnaam, String postcode, String toevoeging, Long huisnummer, String woonplaats, Set<KlantHasAdres> klantHasAdreses) {
       this.adrestype = adrestype;
       this.straatnaam = straatnaam;
       this.postcode = postcode;
       this.toevoeging = toevoeging;
       this.huisnummer = huisnummer;
       this.woonplaats = woonplaats;
       this.klantHasAdreses = klantHasAdreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAdres", unique=true, nullable=false)
    public Long getIdAdres() {
        return this.idAdres;
    }
    
    public void setIdAdres(Long idAdres) {
        this.idAdres = idAdres;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="adresType_idAdresType")
    public Adrestype getAdrestype() {
        return this.adrestype;
    }
    
    public void setAdrestype(Adrestype adrestype) {
        this.adrestype = adrestype;
    }

    
    @Column(name="straatnaam", length=45)
    public String getStraatnaam() {
        return this.straatnaam;
    }
    
    public void setStraatnaam(String straatnaam) {
        this.straatnaam = straatnaam;
    }

    
    @Column(name="postcode", length=45)
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    
    @Column(name="toevoeging", length=45)
    public String getToevoeging() {
        return this.toevoeging;
    }
    
    public void setToevoeging(String toevoeging) {
        this.toevoeging = toevoeging;
    }

    
    @Column(name="huisnummer")
    public Long getHuisnummer() {
        return this.huisnummer;
    }
    
    public void setHuisnummer(Long huisnummer) {
        this.huisnummer = huisnummer;
    }

    
    @Column(name="woonplaats", length=45)
    public String getWoonplaats() {
        return this.woonplaats;
    }
    
    public void setWoonplaats(String woonplaats) {
        this.woonplaats = woonplaats;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="adres")
    public Set<KlantHasAdres> getKlantHasAdreses() {
        return this.klantHasAdreses;
    }
    
    public void setKlantHasAdreses(Set<KlantHasAdres> klantHasAdreses) {
        this.klantHasAdreses = klantHasAdreses;
    }




}


