package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Artikel generated by hbm2java
 */
@Entity
@Table(name="artikel"
    ,catalog="workshop2"
)
public class Artikel  implements java.io.Serializable {


     private Long idArtikel;
     private Long artikelNummer;
     private String naam;
     private String omschrijving;
     private BigDecimal prijs;
     private Long voorraad;
     private Set<BestellingHasArtikel> bestellingHasArtikels = new HashSet<>(0);

    public Artikel() {
    }

    public Artikel(Long artikelNummer, String naam, String omschrijving, BigDecimal prijs, Long voorraad, Set<BestellingHasArtikel> bestellingHasArtikels) {
       this.artikelNummer = artikelNummer;
       this.naam = naam;
       this.omschrijving = omschrijving;
       this.prijs = prijs;
       this.voorraad = voorraad;
       this.bestellingHasArtikels = bestellingHasArtikels;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_artikel", unique=true, nullable=false)
    public Long getIdArtikel() {
        return this.idArtikel;
    }
    
    public void setIdArtikel(Long idArtikel) {
        this.idArtikel = idArtikel;
    }

    
    @Column(name="artikelnummer")
    public Long getArtikelNummer() {
        return this.artikelNummer;
    }
    
    public void setArtikelNummer(Long artikelNummer) {
        this.artikelNummer = artikelNummer;
    }

    
    @Column(name="naam", length=45)
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }

    
    @Column(name="omschrijving", length=225)
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    
    @Column(name="prijs", precision=10)
    public BigDecimal getPrijs() {
        return this.prijs;
    }
    
    public void setPrijs(BigDecimal prijs) {
        this.prijs = prijs;
    }

    
    @Column(name="voorraad")
    public Long getVoorraad() {
        return this.voorraad;
    }
    
    public void setVoorraad(Long voorraad) {
        this.voorraad = voorraad;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="artikel")
    public Set<BestellingHasArtikel> getBestellingHasArtikels() {
        return this.bestellingHasArtikels;
    }
    
    public void setBestellingHasArtikels(Set<BestellingHasArtikel> bestellingHasArtikels) {
        this.bestellingHasArtikels = bestellingHasArtikels;
    }




}


