package com.rsvier.workshop2.MVC.Model.POJO;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BestellingHasArtikelId generated by hbm2java
 */
@Embeddable
public class BestellingHasArtikelId  implements java.io.Serializable {


     private Long bestellingIdBestelling;
     private Long artikelIdArtikel;
     private Integer aantal;

    public BestellingHasArtikelId() {
    }

    public BestellingHasArtikelId(Long bestellingIdBestelling, Long artikelIdArtikel, Integer aantal) {
       this.bestellingIdBestelling = bestellingIdBestelling;
       this.artikelIdArtikel = artikelIdArtikel;
       this.aantal = aantal;
    }
   


    @Column(name="bestelling_idBestelling")
    public Long getBestellingIdBestelling() {
        return this.bestellingIdBestelling;
    }
    
    public void setBestellingIdBestelling(Long bestellingIdBestelling) {
        this.bestellingIdBestelling = bestellingIdBestelling;
    }


    @Column(name="artikel_idArtikel")
    public Long getArtikelIdArtikel() {
        return this.artikelIdArtikel;
    }
    
    public void setArtikelIdArtikel(Long artikelIdArtikel) {
        this.artikelIdArtikel = artikelIdArtikel;
    }


    @Column(name="aantal")
    public Integer getAantal() {
        return this.aantal;
    }
    
    public void setAantal(Integer aantal) {
        this.aantal = aantal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BestellingHasArtikelId) ) return false;
		 BestellingHasArtikelId castOther = ( BestellingHasArtikelId ) other; 
         
		 return ( (this.getBestellingIdBestelling()==castOther.getBestellingIdBestelling()) || ( this.getBestellingIdBestelling()!=null && castOther.getBestellingIdBestelling()!=null && this.getBestellingIdBestelling().equals(castOther.getBestellingIdBestelling()) ) )
 && ( (this.getArtikelIdArtikel()==castOther.getArtikelIdArtikel()) || ( this.getArtikelIdArtikel()!=null && castOther.getArtikelIdArtikel()!=null && this.getArtikelIdArtikel().equals(castOther.getArtikelIdArtikel()) ) )
 && ( (this.getAantal()==castOther.getAantal()) || ( this.getAantal()!=null && castOther.getAantal()!=null && this.getAantal().equals(castOther.getAantal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBestellingIdBestelling() == null ? 0 : this.getBestellingIdBestelling().hashCode() );
         result = 37 * result + ( getArtikelIdArtikel() == null ? 0 : this.getArtikelIdArtikel().hashCode() );
         result = 37 * result + ( getAantal() == null ? 0 : this.getAantal().hashCode() );
         return result;
   }   


}


