package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bestelling generated by hbm2java
 */
@Entity
@Table(name="bestelling"
    ,catalog="workshop2"
)
public class Bestelling  implements java.io.Serializable {


     private Long idBestelling;
     private Klant klant;
     private String bestelNummer;
     private Date bestelDatum;
     private Set<BestellingHasArtikel> bestellingHasArtikels = new HashSet<>(0);

    public Bestelling() {
    }

    public Bestelling(Klant klant, String bestelNummer, Date bestelDatum, Set<BestellingHasArtikel> bestellingHasArtikels) {
       this.klant = klant;
       this.bestelNummer = bestelNummer;
       this.bestelDatum = bestelDatum;
       this.bestellingHasArtikels = bestellingHasArtikels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_bestelling", unique=true, nullable=false)
    public Long getIdBestelling() {
        return this.idBestelling;
    }
    
    public void setIdBestelling(Long idBestelling) {
        this.idBestelling = idBestelling;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klant_id_klant")
    public Klant getKlant() {
        return this.klant;
    }
    
    public void setKlant(Klant klant) {
        this.klant = klant;
    }

    
    @Column(name="bestel_nummer", length=45)
    public String getBestelNummer() {
        return this.bestelNummer;
    }
    
    public void setBestelNummer(String bestelNummer) {
        this.bestelNummer = bestelNummer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bestel_datum", length=19)
    public Date getBestelDatum() {
        return this.bestelDatum;
    }
    
    public void setBestelDatum(Date bestelDatum) {
        this.bestelDatum = bestelDatum;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="bestelling")
    public Set<BestellingHasArtikel> getBestellingHasArtikels() {
        return this.bestellingHasArtikels;
    }
    
    public void setBestellingHasArtikels(Set<BestellingHasArtikel> bestellingHasArtikels) {
        this.bestellingHasArtikels = bestellingHasArtikels;
    }




}


