package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BestellingHasArtikel generated by hbm2java
 */
@Entity
@Table(name="bestelling_has_artikel"
    ,catalog="workshop2"
)
public class BestellingHasArtikel  implements java.io.Serializable {


     private BestellingHasArtikelId id;
     private Artikel artikel;
     private Bestelling bestelling;

    public BestellingHasArtikel() {
    }

	
    public BestellingHasArtikel(BestellingHasArtikelId id) {
        this.id = id;
    }
    public BestellingHasArtikel(BestellingHasArtikelId id, Artikel artikel, Bestelling bestelling) {
       this.id = id;
       this.artikel = artikel;
       this.bestelling = bestelling;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="bestellingIdBestelling", column=@Column(name="bestelling_idBestelling") ), 
        @AttributeOverride(name="artikelIdArtikel", column=@Column(name="artikel_idArtikel") ), 
        @AttributeOverride(name="aantal", column=@Column(name="aantal") ) } )
    public BestellingHasArtikelId getId() {
        return this.id;
    }
    
    public void setId(BestellingHasArtikelId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="artikel_idArtikel", insertable=false, updatable=false)
    public Artikel getArtikel() {
        return this.artikel;
    }
    
    public void setArtikel(Artikel artikel) {
        this.artikel = artikel;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bestelling_idBestelling", insertable=false, updatable=false)
    public Bestelling getBestelling() {
        return this.bestelling;
    }
    
    public void setBestelling(Bestelling bestelling) {
        this.bestelling = bestelling;
    }




}


