package com.rsvier.workshop2.MVC.Model.POJO;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klant generated by hbm2java
 */
@Entity
@Table(name="klant"
    ,catalog="workshop2"
)
public class Klant  implements java.io.Serializable {


     private Long idKlant;
     private Account account;
     private String voornaam;
     private String tussenvoegsel;
     private String achternaam;
     private String email;
     private Set klantHasAdreses = new HashSet(0);
     private Set bestellings = new HashSet(0);

    public Klant() {
    }

    public Klant(Account account, String voornaam, String tussenvoegsel, String achternaam, String email, Set klantHasAdreses, Set bestellings) {
       this.account = account;
       this.voornaam = voornaam;
       this.tussenvoegsel = tussenvoegsel;
       this.achternaam = achternaam;
       this.email = email;
       this.klantHasAdreses = klantHasAdreses;
       this.bestellings = bestellings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idKlant", unique=true, nullable=false)
    public Long getIdKlant() {
        return this.idKlant;
    }
    
    public void setIdKlant(Long idKlant) {
        this.idKlant = idKlant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_idAccount")
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    
    @Column(name="voornaam", length=45)
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }

    
    @Column(name="tussenvoegsel", length=7)
    public String getTussenvoegsel() {
        return this.tussenvoegsel;
    }
    
    public void setTussenvoegsel(String tussenvoegsel) {
        this.tussenvoegsel = tussenvoegsel;
    }

    
    @Column(name="achternaam", length=45)
    public String getAchternaam() {
        return this.achternaam;
    }
    
    public void setAchternaam(String achternaam) {
        this.achternaam = achternaam;
    }

    
    @Column(name="email", length=70)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="klant")
    public Set getKlantHasAdreses() {
        return this.klantHasAdreses;
    }
    
    public void setKlantHasAdreses(Set klantHasAdreses) {
        this.klantHasAdreses = klantHasAdreses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="klant")
    public Set getBestellings() {
        return this.bestellings;
    }
    
    public void setBestellings(Set bestellings) {
        this.bestellings = bestellings;
    }




}


