package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KlantHasAdres generated by hbm2java
 */
@Entity
@Table(name="klant_has_adres"
    ,catalog="workshop2"
)
public class KlantHasAdres  implements java.io.Serializable {


     private KlantHasAdresId id;
     private Adres adres;
     private Klant klant;

    public KlantHasAdres() {
    }

	
    public KlantHasAdres(KlantHasAdresId id) {
        this.id = id;
    }
    public KlantHasAdres(KlantHasAdresId id, Adres adres, Klant klant) {
       this.id = id;
       this.adres = adres;
       this.klant = klant;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="klantIdKlant", column=@Column(name="klant_idKlant") ), 
        @AttributeOverride(name="adresIdAdres", column=@Column(name="adres_idAdres") ) } )
    public KlantHasAdresId getId() {
        return this.id;
    }
    
    public void setId(KlantHasAdresId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="adres_idAdres", insertable=false, updatable=false)
    public Adres getAdres() {
        return this.adres;
    }
    
    public void setAdres(Adres adres) {
        this.adres = adres;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klant_idKlant", insertable=false, updatable=false)
    public Klant getKlant() {
        return this.klant;
    }
    
    public void setKlant(Klant klant) {
        this.klant = klant;
    }




}


