package com.rsvier.workshop2.mvc.model.pojo;
// Generated Nov 24, 2016 9:35:53 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KlantHasAdresId generated by hbm2java
 */
@Embeddable
public class KlantHasAdresId  implements java.io.Serializable {


     private Long klantIdKlant;
     private Long adresIdAdres;

    public KlantHasAdresId() {
    }

    public KlantHasAdresId(Long klantIdKlant, Long adresIdAdres) {
       this.klantIdKlant = klantIdKlant;
       this.adresIdAdres = adresIdAdres;
    }
   


    @Column(name="klant_id_klant")
    public Long getKlantIdKlant() {
        return this.klantIdKlant;
    }
    
    public void setKlantIdKlant(Long klantIdKlant) {
        this.klantIdKlant = klantIdKlant;
    }


    @Column(name="adres_id_adres")
    public Long getAdresIdAdres() {
        return this.adresIdAdres;
    }
    
    public void setAdresIdAdres(Long adresIdAdres) {
        this.adresIdAdres = adresIdAdres;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KlantHasAdresId) ) return false;
		 KlantHasAdresId castOther = ( KlantHasAdresId ) other; 
         
		 return ( (this.getKlantIdKlant()==castOther.getKlantIdKlant()) || ( this.getKlantIdKlant()!=null && castOther.getKlantIdKlant()!=null && this.getKlantIdKlant().equals(castOther.getKlantIdKlant()) ) )
 && ( (this.getAdresIdAdres()==castOther.getAdresIdAdres()) || ( this.getAdresIdAdres()!=null && castOther.getAdresIdAdres()!=null && this.getAdresIdAdres().equals(castOther.getAdresIdAdres()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getKlantIdKlant() == null ? 0 : this.getKlantIdKlant().hashCode() );
         result = 37 * result + ( getAdresIdAdres() == null ? 0 : this.getAdresIdAdres().hashCode() );
         return result;
   }   


}


